language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo bench;
    fi
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --features stats
  - cargo test --features stats
  - cargo build --features datasets
  - cargo test --features datasets